### ISSUE TITLE
Cannot start the console with my own db

### ISSUE THREAD

**Issue by lordkada** [neo4j-contrib/rabbithole#78]
If I run with 
mvn exec:java -Dexec.args="9999 /path/to/my/db expose"

I get this exception:

2014-08-13 16:16:36,476 WARN  - ServletHandler             - /console/init
java.lang.IllegalArgumentException: Could not resolve dependency of type:org.neo4j.kernel.guard.Guard
    at org.neo4j.graphdb.DependencyResolver$Adapter$1.select(DependencyResolver.java:84)
    at org.neo4j.kernel.extension.KernelExtensions.resolveDependency(KernelExtensions.java:206)
    at org.neo4j.kernel.InternalAbstractGraphDatabase$DependencyResolverImpl.resolveDependency(InternalAbstractGraphDatabase.java:1511)
    at org.neo4j.graphdb.DependencyResolver$Adapter.resolveDependency(DependencyResolver.java:92)
    at org.neo4j.community.console.GuardingRequestFilter.getGuard(GuardingRequestFilter.java:26)
    at org.neo4j.community.console.GuardingRequestFilter.doFilter(GuardingRequestFilter.java:54)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
    at org.neo4j.community.console.AllowAjaxFilter.doFilter(AllowAjaxFilter.java:51)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:445)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
    at java.lang.Thread.run(Thread.java:744)

My neo4j version is 2.1.3 (but was the same using 2.1.2)

**Comment by ekkis** [comment]
I'm running 2.2.2 and experience the same problem.  also I installed 1.9.9 but the Console won't run at all against that version

**Comment by jalmasi** [comment]
Needs to be patched:
[arguments.patch.zip](https://github.com/neo4j-contrib/rabbithole/files/6378605/arguments.patch.zip)
